name = "Hyde-502"
license = "MIT"
licenselink = "https://github.com/monamaret/hyde-502/blob/master/LICENSE.md"
description = "Hyde-502, a Hugo theme based on Hyde"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "Mona Maret"
    homepage = "https://monamaret.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
